<?php
    namespace App\Service\Admin\MainPage\GetCompetitionData\CompetitionDataDTO\ResultDTO;

    use App\Entity\MainTable;

    class MainTableResultItemDTO implements ResultItemDTOInterface
    {
        public function __construct(
            private ?int $main_id,
            private ?string $surname_name,
            private ?string $date_of_birth,
            private ?string $bodyweight,
            private ?string $category,
            private ?int $category_num,
            private ?int $grp,
            private ?int $lot,
            private ?string $rank_class,
            private ?string $region,
            private ?string $city,
            private ?string $club,
            private ?string $trener_1,
            private ?string $trener_2,
            private ?string $trener_3,
            private ?string $trener_4,
            private ?string $titles,
            private ?int $personally,
            private ?int $out_of_comp,
            private ?int $md,
            private ?int $dbl,
            private ?string $squat_nom,
            private ?string $bench_press_nom,
            private ?string $deadlift_nom,
            private ?string $total_nom,
            private ?string $squat_1,
            private ?string $squat_1_res,
            private ?string $squat_1_CSS,
            private ?string $squat_1_fcst,
            private ?string $squat_2,
            private ?string $squat_2_res,
            private ?string $squat_2_CSS,
            private ?string $squat_2_fcst,
            private ?string $squat_3,
            private ?string $squat_3_res,
            private ?string $squat_3_CSS,
            private ?string $squat_3_fcst,
            private ?string $squat_4,
            private ?string $squat_4_res,
            private ?string $squat_4_CSS,
            private ?string $squat_4_fcst,
            private ?string $squat_res,
            private ?string $squat_fcst,
            private ?string $bench_press_1,
            private ?string $bench_press_1_res,
            private ?string $bench_press_1_CSS,
            private ?string $bench_press_1_fcst,
            private ?string $bench_press_2,
            private ?string $bench_press_2_res,
            private ?string $bench_press_2_CSS,
            private ?string $bench_press_2_fcst,
            private ?string $bench_press_3,
            private ?string $bench_press_3_res,
            private ?string $bench_press_3_CSS,
            private ?string $bench_press_3_fcst,
            private ?string $bench_press_4,
            private ?string $bench_press_4_res,
            private ?string $bench_press_4_CSS,
            private ?string $bench_press_4_fcst,
            private ?string $bench_press_res,
            private ?string $bench_press_fcst,
            private ?string $deadlift_1,
            private ?string $deadlift_1_res,
            private ?string $deadlift_1_CSS,
            private ?string $deadlift_1_fcst,
            private ?string $deadlift_2,
            private ?string $deadlift_2_res,
            private ?string $deadlift_2_CSS,
            private ?string $deadlift_2_fcst,
            private ?string $deadlift_3,
            private ?string $deadlift_3_res,
            private ?string $deadlift_3_CSS,
            private ?string $deadlift_3_fcst,
            private ?string $deadlift_4,
            private ?string $deadlift_4_res,
            private ?string $deadlift_4_CSS,
            private ?string $deadlift_4_fcst,
            private ?string $deadlift_res,
            private ?string $deadlift_fcst,
            private ?string $total_1_att,
            private ?string $total,
            private ?string $total_fcst,
            private ?string $coef,
            private ?string $coef_squat,
            private ?string $coef_squat_fcst,
            private ?string $coef_bench_press,
            private ?string $coef_bench_press_fcst,
            private ?string $coef_deadlift,
            private ?string $coef_deadlift_fcst,
            private ?string $coef_total,
            private ?string $coef_total_fcst,
            private ?int $squat_rnk,
            private ?int $squat_rnk_fcst,
            private ?int $bench_press_rnk,
            private ?int $bench_press_rnk_fcst,
            private ?int $deadlift_rnk,
            private ?int $deadlift_rnk_fcst,
            private ?int $ranking,
            private ?int $rnk_fcst,
            private ?int $points,
            private ?int $points_bp,
            private ?int $comp_id
        ) {}

        public static function fromEntity(Competitions $e): self
        {
            return new self(
                $e ->getId(),
                $e ->getSurnameName(),
                $e ->getDateOfBirth(),
                $e ->getBodyweight(),
                $e ->getCategory(),
                $e ->getCategoryNum(),
                $e ->getGrp(),
                $e ->getLot(),
                $e ->getRankClass(),
                $e ->getRegion(),
                $e ->getCity(),
                $e ->getClub(),
                $e ->getTrener1(),
                $e ->getTrener2(),
                $e ->getTrener3(),
                $e ->getTrener4(),
                $e ->getTitles(),
                $e ->getPersonally(),
                $e ->getOutOfComp(),
                $e ->getMd(),
                $e ->getDbl(),
                $e ->getSquatNom(),
                $e ->getBenchPressNom(),
                $e ->getDeadliftNom(),
                $e ->getTotalNom(),
                $e ->getSquat1(),
                $e ->getSquat1Res(),
                $e ->getSquat1CSS(),
                $e ->getSquat1Fcst(),
                $e ->getSquat2(),
                $e ->getSquat2Res(),
                $e ->getSquat2CSS(),
                $e ->getSquat2Fcst(),
                $e ->getSquat3(),
                $e ->getSquat3Res(),
                $e ->getSquat3CSS(),
                $e ->getSquat3Fcst(),
                $e ->getSquat4(),
                $e ->getSquat4Res(),
                $e ->getSquat4CSS(),
                $e ->getSquat4Fcst(),
                $e ->getSquatRes(),
                $e ->getSquatFcst(),
                $e ->getBenchPress1(),
                $e ->getBenchPress1Res(),
                $e ->getBenchPress1CSS(),
                $e ->getBenchPress1Fcst(),
                $e ->getBenchPress2(),
                $e ->getBenchPress2Res(),
                $e ->getBenchPress2CSS(),
                $e ->getBenchPress2Fcst(),
                $e ->getBenchPress3(),
                $e ->getBenchPress3Res(),
                $e ->getBenchPress3CSS(),
                $e ->getBenchPress3Fcst(),
                $e ->getBenchPress4(),
                $e ->getBenchPress4Res(),
                $e ->getBenchPress4CSS(),
                $e ->getBenchPress4Fcst(),
                $e ->getBenchPressRes(),
                $e ->getBenchPressFcst(),
                $e ->getDeadlift1(),
                $e ->getDeadlift1Res(),
                $e ->getDeadlift1CSS(),
                $e ->getDeadlift1Fcst(),
                $e ->getDeadlift2(),
                $e ->getDeadlift2Res(),
                $e ->getDeadlift2CSS(),
                $e ->getDeadlift2Fcst(),
                $e ->getDeadlift3(),
                $e ->getDeadlift3Res(),
                $e ->getDeadlift3CSS(),
                $e ->getDeadlift3Fcst(),
                $e ->getDeadlift4(),
                $e ->getDeadlift4Res(),
                $e ->getDeadlift4CSS(),
                $e ->getDeadlift4Fcst(),
                $e ->getDeadliftRes(),
                $e ->getDeadliftFcst(),
                $e ->getTotal1Att(),
                $e ->getTotal(),
                $e ->getTotalFcst(),
                $e ->getCoef(),
                $e ->getCoefSquat(),
                $e ->getCoefSquatFcst(),
                $e ->getCoefBenchPress(),
                $e ->getCoefBenchPressFcst(),
                $e ->getCoefDeadlift(),
                $e ->getCoefDeadliftFcst(),
                $e ->getCoefTotal(),
                $e ->getCoefTotalFcst(),
                $e ->getSquatRnk(),
                $e ->getSquatRnkFcst(),
                $e ->getBenchPressRnk(),
                $e ->getBenchPressRnkFcst(),
                $e ->getDeadliftRnk(),
                $e ->getDeadliftRnkFcst(),
                $e ->getRanking(),
                $e ->getRnkFcst(),
                $e ->getPoints(),
                $e ->getPointsBp(),
                $e ->getCompetition()
            );
        }

        public function toArray(): array
        {
            return [
                'main_id'               => $this -> main_id,
                'surname_name'          => $this -> surname_name,
                'date_of_birth'         => $this -> date_of_birth?->format('Y-m-d'),
                'bodyweight'            => $this -> bodyweight,
                'category'              => $this -> category,
                'category_num'          => $this -> category_num,
                'grp'                   => $this -> grp,
                'lot'                   => $this -> lot,
                'rank_class'            => $this -> rank_class,
                'region'                => $this -> region,
                'city'                  => $this -> city,
                'club'                  => $this -> club,
                'trener_1'              => $this -> trener_1,
                'trener_2'              => $this -> trener_2,
                'trener_3'              => $this -> trener_3,
                'trener_4'              => $this -> trener_4,
                'titles'                => $this -> titles,
                'personally'            => $this -> personally,
                'out_of_comp'           => $this -> out_of_comp,
                'md'                    => $this -> md,
                'dbl'                   => $this -> dbl,
                'squat_nom'             => $this -> squat_nom,
                'bench_press_nom'       => $this -> bench_press_nom,
                'deadlift_nom'          => $this -> deadlift_nom,
                'total_nom'             => $this -> total_nom,
                'squat_1'               => $this -> squat_1,
                'squat_1_res'           => $this -> squat_1_res,
                'squat_1_CSS'           => $this -> squat_1_CSS,
                'squat_1_fcst'          => $this -> squat_1_fcst,
                'squat_2'               => $this -> squat_2,
                'squat_2_res'           => $this -> squat_2_res,
                'squat_2_CSS'           => $this -> squat_2_CSS,
                'squat_2_fcst'          => $this -> squat_2_fcst,
                'squat_3'               => $this -> squat_3,
                'squat_3_res'           => $this -> squat_3_res,
                'squat_3_CSS'           => $this -> squat_3_CSS,
                'squat_3_fcst'          => $this -> squat_3_fcst,
                'squat_4'               => $this -> squat_4,
                'squat_4_res'           => $this -> squat_4_res,
                'squat_4_CSS'           => $this -> squat_4_CSS,
                'squat_4_fcst'          => $this -> squat_4_fcst,
                'squat_res'             => $this -> squat_res,
                'squat_fcst'            => $this -> squat_fcst,
                'bench_press_1'         => $this -> bench_press_1,
                'bench_press_1_res'     => $this -> bench_press_1_res,
                'bench_press_1_CSS'     => $this -> bench_press_1_CSS,
                'bench_press_1_fcst'    => $this -> bench_press_1_fcst,
                'bench_press_2'         => $this -> bench_press_2,
                'bench_press_2_res'     => $this -> bench_press_2_res,
                'bench_press_2_CSS'     => $this -> bench_press_2_CSS,
                'bench_press_2_fcst'    => $this -> bench_press_2_fcst,
                'bench_press_3'         => $this -> bench_press_3,
                'bench_press_3_res'     => $this -> bench_press_3_res,
                'bench_press_3_CSS'     => $this -> bench_press_3_CSS,
                'bench_press_3_fcst'    => $this -> bench_press_3_fcst,
                'bench_press_4'         => $this -> bench_press_4,
                'bench_press_4_res'     => $this -> bench_press_4_res,
                'bench_press_4_CSS'     => $this -> bench_press_4_CSS,
                'bench_press_4_fcst'    => $this -> bench_press_4_fcst,
                'bench_press_res'       => $this -> bench_press_res,
                'bench_press_fcst'      => $this -> bench_press_fcst,
                'deadlift_1'            => $this -> deadlift_1,
                'deadlift_1_res'        => $this -> deadlift_1_res,
                'deadlift_1_CSS'        => $this -> deadlift_1_CSS,
                'deadlift_1_fcst'       => $this -> deadlift_1_fcst,
                'deadlift_2'            => $this -> deadlift_2,
                'deadlift_2_res'        => $this -> deadlift_2_res,
                'deadlift_2_CSS'        => $this -> deadlift_2_CSS,
                'deadlift_2_fcst'       => $this -> deadlift_2_fcst,
                'deadlift_3'            => $this -> deadlift_3,
                'deadlift_3_res'        => $this -> deadlift_3_res,
                'deadlift_3_CSS'        => $this -> deadlift_3_CSS,
                'deadlift_3_fcst'       => $this -> deadlift_3_fcst,
                'deadlift_4'            => $this -> deadlift_4,
                'deadlift_4_res'        => $this -> deadlift_4_res,
                'deadlift_4_CSS'        => $this -> deadlift_4_CSS,
                'deadlift_4_fcst'       => $this -> deadlift_4_fcst,
                'deadlift_res'          => $this -> deadlift_res,
                'deadlift_fcst'         => $this -> deadlift_fcst,
                'total_1_att'           => $this -> total_1_att,
                'total'                 => $this -> total,
                'total_fcst'            => $this -> total_fcst,
                'coef'                  => $this -> coef,
                'coef_squat'            => $this -> coef_squat,
                'coef_squat_fcst'       => $this -> coef_squat_fcst,
                'coef_bench_press'      => $this -> coef_bench_press,
                'coef_bench_press_fcst' => $this -> coef_bench_press_fcst,
                'coef_deadlift'         => $this -> coef_deadlift,
                'coef_deadlift_fcst'    => $this -> coef_deadlift_fcst,
                'coef_total'            => $this -> coef_total,
                'coef_total_fcst'       => $this -> coef_total_fcst,
                'squat_rnk'             => $this -> squat_rnk,
                'squat_rnk_fcst'        => $this -> squat_rnk_fcst,
                'bench_press_rnk'       => $this -> bench_press_rnk,
                'bench_press_rnk_fcst'  => $this -> bench_press_rnk_fcst,
                'deadlift_rnk'          => $this -> deadlift_rnk,
                'deadlift_rnk_fcst'     => $this -> deadlift_rnk_fcst,
                'ranking'               => $this -> ranking,
                'rnk_fcst'              => $this -> rnk_fcst,
                'points'                => $this -> points,
                'points_bp'             => $this -> points_bp,
                'comp_id'               => $this -> comp_id
            ];
        }
    }
?>